name: Publish Package

on:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'

      - name: Install npm dependencies
        run: npm install
        working-directory: ./package

      # Publish unscoped to npmjs.org
      - name: Create .npmrc for npmjs.org
        run: echo "registry=https://registry.npmjs.org/" > .npmrc
        working-directory: ./package

      - name: Publish to npmjs.org
        run: npm publish --access public
        working-directory: ./package

      # Rename package.json & lockfile to scoped for GitHub Packages
      - name: Scope package name for GitHub Packages
        run: |
          jq '.name = "@monitio/" + .name' package/package.json > package/tmp.json
          mv package/tmp.json package/package.json
          if [ -f package/package-lock.json ]; then \
            jq '.name = "@monitio/" + .name' package/package-lock.json > package/tmp-lock.json; \
            mv package/tmp-lock.json package/package-lock.json; \
          fi

      - name: Create .npmrc for GitHub Packages
        run: |
          echo "@monitio:registry=https://npm.pkg.github.com" > package/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> package/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: npm publish --access public
        working-directory: ./package
