name: Publish Package

on:
  release:
    types:
      - published

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Setup Node for npmjs.org (root-level)
      - name: Setup Node.js for npmjs.org
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'
          registry-url: 'https://registry.npmjs.org'

      # 3) Authenticate against npmjs.org (root-level .npmrc)
      - name: Authenticate with npmjs.org
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # 4) Install & publish to npmjs.org (inside package/)
      - name: Install & Publish to npmjs.org
        working-directory: ./package
        run: |
          npm install
          npm publish --access public

      # 5) Rewrite package name to scoped for GitHub Packages (inside package/)
      - name: Scope package name for GitHub Packages
        working-directory: ./package
        run: |
          jq '.name = "@monitio/" + .name' package.json > tmp.json && mv tmp.json package.json
          if [ -f package-lock.json ]; then
            jq '.name = "@monitio/" + .name' package-lock.json > tmp-lock.json && mv tmp-lock.json package-lock.json
          fi

      # 6) Setup Node for GitHub Packages (root-level)
      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v3
        with:
          node-version: '23.7.0'
          registry-url: 'https://npm.pkg.github.com'

      # 7) Authenticate against GitHub Packages (root-level .npmrc)
      - name: Authenticate with GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ~/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 8) Publish to GitHub Packages (inside package/)
      - name: Publish to GitHub Packages
        working-directory: ./package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
